---
title: PayRequest.nl | Simple fast payment links
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: payrequest.nl site
description: Lets you easily create payment links and share them via email or sms,
  we support all payment methods directly via your current payment provider.
markdown: kramdown
plugins:
  - jekyll-sitemap
